In [439]:
import numpy as np
import pandas as pd
from fastai.vision import *

In [440]:
n = 225
a = np.arange(1,n/2)
modulus = n%a

In [441]:
np.set_printoptions(edgeitems=300, linewidth=100000,formatter=dict(float=lambda x: "%1.1f" % x))

In [442]:
compressed = np.compress(modulus==0,a);compressed

array([1.0, 3.0, 5.0, 9.0, 15.0, 25.0, 45.0, 75.0])

In [443]:
truth = compressed[:,None]%compressed;

In [444]:
print('    ',compressed)
print('   | -------------------------------------------')
[i for i in zip(compressed[:,None],compressed[:,None]%compressed)]
for i in range(len(truth)):
    print(f'{compressed[i]:2.3g} | {truth[i]:}')

     [1.0 3.0 5.0 9.0 15.0 25.0 45.0 75.0]
   | -------------------------------------------
 1 | [0.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0]
 3 | [0.0 0.0 3.0 3.0 3.0 3.0 3.0 3.0]
 5 | [0.0 2.0 0.0 5.0 5.0 5.0 5.0 5.0]
 9 | [0.0 0.0 4.0 0.0 9.0 9.0 9.0 9.0]
15 | [0.0 0.0 0.0 6.0 0.0 15.0 15.0 15.0]
25 | [0.0 1.0 0.0 7.0 10.0 0.0 25.0 25.0]
45 | [0.0 0.0 0.0 0.0 0.0 20.0 0.0 45.0]
75 | [0.0 0.0 0.0 3.0 0.0 0.0 30.0 0.0]


In [445]:
print(compressed)

[1.0 3.0 5.0 9.0 15.0 25.0 45.0 75.0]


In [446]:
divide = compressed[:,None]/compressed;

In [447]:
print('      ',compressed)
print('   | -------------------------------------------')
[i for i in zip(compressed[:,None],compressed[:,None]%compressed)]
for i in range(len(divide)):
    print(f'{compressed[i]:4.0f} | {divide[i]:}')

       [1.0 3.0 5.0 9.0 15.0 25.0 45.0 75.0]
   | -------------------------------------------
   1 | [1.0 0.3 0.2 0.1 0.1 0.0 0.0 0.0]
   3 | [3.0 1.0 0.6 0.3 0.2 0.1 0.1 0.0]
   5 | [5.0 1.7 1.0 0.6 0.3 0.2 0.1 0.1]
   9 | [9.0 3.0 1.8 1.0 0.6 0.4 0.2 0.1]
  15 | [15.0 5.0 3.0 1.7 1.0 0.6 0.3 0.2]
  25 | [25.0 8.3 5.0 2.8 1.7 1.0 0.6 0.3]
  45 | [45.0 15.0 9.0 5.0 3.0 1.8 1.0 0.6]
  75 | [75.0 25.0 15.0 8.3 5.0 3.0 1.7 1.0]


In [433]:
27*25*4

2700